### PR TITLE
Test fix to add modal behaviour in activity chooser

### PR DESCRIPTION
**Pull request by Pro-Panda**

### CODE REVIEW

**Comment by Pro-Panda** [comment]
@quozl, while the `activity chooser` window persists even after clicking anywhere on the rest of the window, but the rest of the window is not disabled. I am able to click buttons and write in text fields

Any suggestions on where I am going wrong

**Comment by Pro-Panda** [comment]
Update: The window doesn't persist when we click outside the window the first time; it hides. It reappears on hovering the mouse in the bottom right corner.
After this, the window doesn't hide

**Comment by quozl** [comment]
I agree, the window is not modal even though it should be.  Reproduced on Fedora 18.

**Comment by Pro-Panda** [comment]
Closed in favor of #2

**Pull request closed without merging**
